### ISSUE TITLE
Version update!

### ISSUE THREAD

**Issue by allenz-me** [cognitive-class/wechat-watson-conversation#1]
Watson conversation have been updated to waston assistant and the API changed too.

So can I use your code to deploy my watson assistant on my wechat public platform at present?

**Comment by michaellzc** [comment]
@wunian12138 Hi, thanks for reaching out. We're in the process of rewriting the library to adopt the new V2 API. Please stay tuned.

**Comment by michaellzc** [comment]
> Watson conversation have been updated to waston assistant and the API changed too.
> 
> So can I use your code to deploy my watson assistant on my wechat public platform at present?

Hi @wunian12138 We have release a new version at https://github.com/IBM/watson-assistant-for-wechat which adapts the V2 API.

doc: https://github.com/IBM/watson-assistant-for-wechat/wiki/How-to-run
